services:
  - type: web
    name: crm-backend-simple
    env: node
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: "4000"
